/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef FLYMOB_AUTODEFS_H
#define FLYMOB_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_FLYMOB_NAME "FlyMob"
#define S3E_EXT_FLYMOB_HASH 0xfdb3c38e

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("FlyMob", 16)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !FLYMOB_AUTODEFS_H */
