/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_FLYMOB_H
#define S3E_EXT_FLYMOB_H

#include <s3eTypes.h>

enum FlyMobInterstitialCallback
{
	S3E_FLYMOB_INTERSTITIAL_DID_LOAD,
	S3E_FLYMOB_INTERSTITIAL_DID_FAIL,
	S3E_FLYMOB_INTERSTITIAL_DID_SHOW,
	S3E_FLYMOB_INTERSTITIAL_DID_CLICK,
	S3E_FLYMOB_INTERSTITIAL_DID_CLOSE,
	S3E_FLYMOB_INTERSTITIAL_DID_EXPIRE,
	S3E_FLYMOB_INTERSTITIAL_MAX
};

enum FlyMobRewardedVideoCallback
{
	S3E_FLYMOB_REWARDED_VIDEO_DID_LOAD,
	S3E_FLYMOB_REWARDED_VIDEO_DID_FAIL,
	S3E_FLYMOB_REWARDED_VIDEO_DID_SHOW,
	S3E_FLYMOB_REWARDED_VIDEO_DID_COMPLETE,
	S3E_FLYMOB_REWARDED_VIDEO_DID_START,
	S3E_FLYMOB_REWARDED_VIDEO_DID_CLOSE,
	S3E_FLYMOB_REWARDED_VIDEO_DID_EXPIRE,
	S3E_FLYMOB_REWARDED_VIDEO_MAX
};
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Report if the FlyMob extension is available.
 * @return S3E_TRUE if the FlyMob extension is available. S3E_FALSE otherwise.
 */
s3eBool FlyMobAvailable();

void s3eFlyMobInterstitialInitialize(const int zoneID);

void s3eFlyMobInterstitialLoad();

void s3eFlyMobInterstitialShow();

bool s3eFlyMobInterstitialIsReady();

void s3eFlyMobRewardedVideoInitialize(const int zoneID);

void s3eFlyMobRewardedVideoLoad();

void s3eFlyMobRewardedVideoShow();

bool s3eFlyMobRewardedVideoIsReady();

void s3eFlyMobSDKSetDebugMode(bool isDebug);

bool s3eFlyMobSDKIsDebugMode();

void s3eFlyMobSDKSetCoppa(bool isCoppa);

bool s3eFlyMobSDKIsCoppa();

void s3eFlyMobSDKSetDnt(bool isDnt);

bool s3eFlyMobSDKIsDnt();

void s3eFlyMobSDKSetTesting(bool isTesting);

bool s3eFlyMobSDKIsTesting();

// \cond HIDDEN_DEFINES
S3E_END_C_DECL
// \endcond

#endif /* !S3E_EXT_FLYMOB_H */
